LOAD DATA CHARACTERSET AL32UTF8
INFILE 'JIGYOSYO.CSV'
BADFILE 'JIGYOSYO.BAD'
DISCARDFILE 'JIGYOSYO.DSC'
TRUNCATE
INTO TABLE OFFICE_ZIP_CODES_WORK
FIELDS TERMINATED BY ','
(
  JIS_CODE_OF_LOCATION
  , OFFICE_NAME_KANA BY '"'
  , OFFICE_NAME BY '"'
  , PREFECTURE_NAME BY '"'
  , CITY_NAME BY '"'
  , TOWN_AREA_NAME BY '"'
  , REST_PART_OF_ADDRESS BY '"'
  , OFFICE_ZIP_CODE BY '"'
  , OLD_ZIP_CODE BY '"'
  , DISTRIBUTOR BY '"'
  , ZIP_CODE_TYPE
  , MULTIPLE_CODE_EXISTS_FLAG
  , REVISION_CODE
)
