INSERT INTO OFFICE_ZIP_CODES (
  ID
  , JIS_CODE_OF_LOCATION
  , OFFICE_NAME_KANA
  , OFFICE_NAME
  , PREFECTURE_NAME
  , CITY_NAME
  , TOWN_AREA_NAME
  , REST_PART_OF_ADDRESS
  , OFFICE_ZIP_CODE
  , OLD_ZIP_CODE
  , DISTRIBUTOR
  , ZIP_CODE_TYPE
  , MULTIPLE_CODE_EXISTS_FLAG
  , REVISION_CODE
) SELECT
  OFFICE_ZIP_CODES_SEQ.nextval
  , JIS_CODE_OF_LOCATION
  , OFFICE_NAME_KANA
  , OFFICE_NAME
  , PREFECTURE_NAME
  , CITY_NAME
  , TOWN_AREA_NAME
  , REST_PART_OF_ADDRESS
  , OFFICE_ZIP_CODE
  , OLD_ZIP_CODE
  , DISTRIBUTOR
  , ZIP_CODE_TYPE
  , MULTIPLE_CODE_EXISTS_FLAG
  , REVISION_CODE
FROM
  OFFICE_ZIP_CODES_WORK
WHERE
  REVISION_CODE IN ('0', '1')
;

EXIT
