SELECT
	  MAX(NVL(LENGTH(JIS_CODE_OF_LOCATION), 0)) AS  JIS_CODE_OF_LOCATION
	, MAX(NVL(LENGTH(OFFICE_NAME_KANA), 0)) AS  OFFICE_NAME_KANA
	, MAX(NVL(LENGTH(OFFICE_NAME), 0)) AS  OFFICE_NAME
	, MAX(NVL(LENGTH(PREFECTURE_NAME), 0)) AS  PREFECTURE_NAME
	, MAX(NVL(LENGTH(CITY_NAME), 0)) AS  CITY_NAME
	, MAX(NVL(LENGTH(TOWN_AREA_NAME), 0)) AS  TOWN_AREA_NAME
	, MAX(NVL(LENGTH(REST_PART_OF_ADDRESS), 0)) AS  REST_PART_OF_ADDRESS
	, MAX(NVL(LENGTH(OFFICE_ZIP_CODE), 0)) AS  OFFICE_ZIP_CODE
	, MAX(NVL(LENGTH(OLD_ZIP_CODE), 0)) AS  OLD_ZIP_CODE
	, MAX(NVL(LENGTH(DISTRIBUTOR), 0)) AS  DISTRIBUTOR
	, MAX(NVL(LENGTH(ZIP_CODE_TYPE), 0)) AS  ZIP_CODE_TYPE
	, MAX(NVL(LENGTH(MULTIPLE_CODE_EXISTS_FLAG), 0)) AS  MULTIPLE_CODE_EXISTS_FLAG
	, MAX(NVL(LENGTH(REVISION_CODE), 0)) AS  REVISION_CODE
FROM
	ZIP_CODE.OFFICE_ZIP_CODES_WORK;
