-- 郵便番号データ桁数確認用
SELECT
  MAX(NVL(LENGTH(JAPANESE_LOCAL_GOVERMENT_CODE), 0)) AS JAPANESE_LOCAL_GOVERMENT_CODE
  , MAX(NVL(LENGTH(OLD_ZIP_CODE), 0)) AS OLD_ZIP_CODE
  , MAX(NVL(LENGTH(ZIP_CODE), 0)) AS ZIP_CODE
  , MAX(NVL(LENGTH(PREFECTURE_NAME_KANA), 0)) AS PREFECTURE_NAME_KANA
  , MAX(NVL(LENGTH(CITY_NAME_KANA), 0)) AS CITY_NAME_KANA
  , MAX(NVL(LENGTH(TOWN_NAME_KANA), 0)) AS TOWN_NAME_KANA
  , MAX(NVL(LENGTH(PREFECTURE_NAME), 0)) AS PREFECTURE_NAME
  , MAX(NVL(LENGTH(CITY_NAME), 0)) AS CITY_NAME
  , MAX(NVL(LENGTH(TOWN_NAME), 0)) AS TOWN_NAME
  , MAX(NVL(LENGTH(TOWN_DEVIDED_FLAG), 0)) AS TOWN_DEVIDED_FLAG
  , MAX(NVL(LENGTH(ISSUED_PER_KOAZA_FLAG), 0)) AS ISSUED_PER_KOAZA_FLAG
  , MAX(NVL(LENGTH(CHOME_TOWN_FLAG), 0)) AS CHOME_TOWN_FLAG
  , MAX(NVL(LENGTH(HAS_MULTIPLE_TOWN_FLAG), 0)) AS HAS_MULTIPLE_TOWN_FLAG
  , MAX(NVL(LENGTH(UPDATE_DISPLAY_FLAG), 0)) AS UPDATE_DISPLAY_FLAG
  , MAX(NVL(LENGTH(CHANGE_REASON_FLAG), 0)) AS CHANGE_REASON_FLAG
FROM
  ZIP_CODES_WORK;
