SELECT
	ZC.*
FROM
	(
	SELECT
		SUBSTR(JAPANESE_LOCAL_GOVERMENT_CODE, 1, 2) AS PREFECTURE_CODE
	,
		MIN(ID) AS MIN_ID
	FROM
		ZIP_CODE.ZIP_CODES
	GROUP BY
		SUBSTR(JAPANESE_LOCAL_GOVERMENT_CODE, 1, 2)
) SQ
INNER JOIN
ZIP_CODE.ZIP_CODES ZC
	ON
	ZC.ID = SQ.MIN_ID;